theme: jekyll-theme-hacker

title: mikerobertson.info
description: a blog

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

topics:

  - name: Python
    web_url: https://github.com/topics/python
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/python/python.png

  - name: ES6
    web_url: https://github.com/topics/ES6
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/es6/es6.png

  - name: Express
    web_url: https://github.com/topics/Express
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/express/express.png

  - name: Javascript
    web_url: https://github.com/topics/Javascript
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/javascript/javascript.png

  - name: NodeJS
    web_url: https://github.com/topics/nodejs
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/nodejs/nodejs.png

  - name: Raspberry Pi
    web_url: https://github.com/topics/raspberry-pi
    image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/raspberry-pi/raspberry-pi.png

  - name: PowerShell
    web_url: https://github.com/PowerShell
    image_url: https://avatars2.githubusercontent.com/u/11524380

  - name: Gothic Horror
    web_url: https://en.wikipedia.org/wiki/Gothic_fiction

  - name: Weird Fiction
    web_url: https://en.wikipedia.org/wiki/Weird_fiction

  - name: Retrowave
    web_url: https://radio.newretrowave.com/

  - name: Slack
    image_url: assets/img/bobdobbs.png
